# Generated by Django 4.0.6 on 2022-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sword',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
