# Generated by Django 4.0.6 on 2022-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sword_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword',
            name='image',
            field=models.ImageField(null=True, upload_to='swords/'),
        ),
    ]
