# Generated by Django 4.0.6 on 2022-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sword',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
