# Generated by Django 4.0.6 on 2022-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sword_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
