# Generated by Django 4.0.6 on 2022-10-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_sword_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
